config/routes.rb
Rails.application.routes.draw do

  resources :events
  root :to => 'users#index'

  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  post '/events/:id/invite', to: 'events#invite'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  validates :name, :description, :date, presence: true
  has_and_belongs_to_many :attendees, join_table: 'users_events', class_name: 'User'

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 4..15 }, uniqueness: true
  has_many :events, foreign_key: :creator_id
  has_and_belongs_to_many :attended_events, join_table: 'users_events', class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_signed_in?
  helper_method :current_user
  helper_method :current_user_name

  def save_user_session(user)
    session[:user_id] = user.id
  end

  def user_signed_in?
    session[:user_id]
  end

  def current_user
    user_id = session[:user_id]
    User.find user_id
  end

  def current_user_name
    user_id = session[:user_id]
    if user_id
      User.find(user_id).name
    else
      ''
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show]
  before_action :authorize, only: %i[new]
  helper_method :invite_path

  def invite_path(event, new_attendee)
    "/events/#{event.id}/invite?new_attendee=#{new_attendee.id}"
  end

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  # Exclude current attendees and the event creator from the all the users,
  # the result is a list of the people that is possible to invite to the event.
  # The equivalent query:
  # select users.name
  # from users
  # where users.name not in
  #       (select u.name
  #        from events
  #                 join users_events ue on events.id = ue.event_id
  #                 join users u on u.id = ue.user_id
  #        where events.id = :current_event)
  # and users.name != :event_creator_name
  def show
    @attendees = Event.joins(:attendees)
      .where(events: { id: @event.id })
      .select('users.name')

    @possible_attendees = User.where.not(name: @attendees)
      .and(User.where.not(name: current_user_name))
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite
    event_id = params[:id]
    event = Event.find event_id
    new_attendee = User.find params[:new_attendee]
    event.attendees << new_attendee
    redirect_to event_path id: event_id
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :date)
  end

  def authorize
    return if user_signed_in?

    flash[:error] = 'Login before creating an Event'
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by name: params[:name]
    if user
      save_user_session user
      redirect_to root_url
    else
      flash[:error] = 'That user does not exist...'
      render 'new'
    end
  end

  def destroy
    session.clear
    flash[:notice] = 'Sign out succesfully'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @prev_events = @user.attended_events.where('date < ?', Time.now)
    @upcoming_events = @user.attended_events.where('date >= ?', Time.now)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        save_user_session @user
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: root_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: current_user.events.build) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <br>
  <%= form.datetime_field :date %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Previous events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Event.past.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Upcoming events</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% Event.upcoming.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.description %></td>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<label>Description: <%= @event.description %></label>
<label>Creator: <%= @event.creator.name %></label>
<label>Date: <%= @event.date %></label>
<h2>Attendees</h2>
<% @event.attendees.each do |attendee| %>
  <label><%= attendee.name %></label>
<% end %>

<br>

<h2>Invite some people!</h2>
<table>
  <% @possible_attendees.each do |attendee| %>
    <tr>
      <th><%= attendee.name %></th>
      <th><%= link_to 'Invite', invite_path(@event, attendee), method: :post %></th>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Users', root_path %> |
    <%= link_to 'Events', events_path %> |
    <%= link_to 'New event', new_event_path %> |
    <% if user_signed_in? %>
      <%= link_to 'Sign Out', '/sign_out', { method: :delete }%>
      <label> Current user: <%= current_user_name  %></label>
    <% else %>
      <%= link_to 'Sign In', '/sign_in' %> |
      <%= link_to 'Sign Up', '/sign_up' %>
    <% end %>



    <% if flash[:error] %>
      <label>Error: <%= flash[:error] %></label>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, url: '/sign_up') do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<label>Name: <%= @user.name %></label>

<br>

<h2>Event list:</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
  </tr>
  <% @user.events.each do |event| %>
    <tr>
      <th><%= event.name %></th>
      <th><%= event.description %></th>
      <th><%= event.date %></th>
    </tr>
  <% end %>
</table>
<h2>Previously attended events</h2>
<% @prev_events.each do |event| %>
  <label><%= event.name %></label>
<% end %>

<br>

<h2>Upcoming events</h2>
<% @upcoming_events.each do |event| %>
  <label><%= event.name %></label>
<% end %>

<% if current_user_name == @user.name %>
  <%= link_to 'New', new_event_path %> |
<% end %>
<%= link_to 'Back', users_path %>